### ISSUE TITLE
你的博客的背景动画

### ISSUE THREAD

**Issue by jfyear1994** [wclimb/wclimb.github.io#1]
你的博客的背景动画使用canvas做的吗？
http://www.wclimb.site
![111](https://user-images.githubusercontent.com/21995695/32424904-3e41f7a6-c2ea-11e7-80d9-0e28ea122742.png)
求分享^_^

**Comment by wunci** [comment]
@jiafulu 这个是主题自带的，有好几种，这个是canvas动画，具体我忘记叫什么名字了
